steps:
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', '--depth=1', 'https://source.developers.google.com/p/ndjokka/r/bogard-new', 'cod']

  - name: 'python'
    args: ['pip3', 'install', '-r', 'cod/requirements.txt']


  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'functions'
      - 'deploy'
      - 'bogard'
      - '--runtime'
      - 'python310'
      - '--trigger-topic'
      - 'bogard'
      - '--entry-point'
      - 'main_call_fun'
      - '--memory'
      - '512MB'
      - '--timeout'
      - '300s'

# - name: 'gcr.io/cloud-builders/gcloud-slim'
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'functions'
      - 'call'
      - 'gcp-iam'
      - '--region=us-central1'  # Replace with your Cloud Function region
      - '--data'  # Add any payload data if your function expects it
      - '{}'

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Waiting for 30 seconds..."
        sleep 60
    id: 'wait-60-seconds'

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['functions', 'delete', 'bogard', '--region', 'us-central1']
    waitFor: ['wait-60-seconds']

options:
  logging: CLOUD_LOGGING_ONLY
